### ISSUE TITLE
Incompatible with utoipa crate

### ISSUE THREAD

**Issue by DenuxPlays** [ranger-ross/actix-web-validation#16]
Hey,

I wanted to implement this crate into my backend.
We use the utoipa crate to generate OpenAPI documentation but unfortunately this validation library is not compatible with utoipa.
I am not sure if the issue should be opened here or at utoipa but other validation libraries seem to work with it completely fine.

## Error:

![image](https://github.com/user-attachments/assets/2b3c547e-7bce-429f-a71a-4cfc7cd7f5a5)

## How to reproduce 

1. Checkout: https://github.com/jt-foss/financrr-app/tree/backend/feature/new-validation-library/backend
2. run `cargo build`
3. take a look at the first error (other errors are all related to the macro failing.)

**Comment by ranger-ross** [comment]
Thanks for the report. Yeah, I would like very much for this library to be compatible with utoipa. I don't know which crate would need to make a change yet. I will look into the implementation details this weekend.

**Comment by DenuxPlays** [comment]
Hey,

I opened an issue at utoipa as ai am not sure if the issue is here or at the other library.

**Comment by juhaku** [comment]
If the syntax in your code is something like in the example in the README.md then I believe that the issue lies in the `utoipa` since I guess it might not be able to correctly parse the `Validated<Json<Example>>` wrappper. 
```rust
async fn hello(Validated(Json(payload)): Validated<Json<Example>>) -> impl Responder {
    HttpResponse::Ok().body(format!("Hello {}", payload.name))
}
```

I am now implementing a fix for this here https://github.com/juhaku/utoipa/pull/977

**Comment by juhaku** [comment]
Though the fix is not expected to be released separately but will eventually land in utoipa `5.0.0`. For time being you can reference in your `Cargo.toml` to the latest commit on master which will have the fix. The 5.0.0 will have some breaking changes and one of them is upgrading to OpenAPI 3.1. But for now it is still in 3.0

**Comment by DenuxPlays** [comment]
> Though the fix is not expected to be released separately but will eventually land in utoipa `5.0.0`. For time being you can reference in your `Cargo.toml` to the latest commit on master which will have the fix. The 5.0.0 will have some breaking changes and one of them is upgrading to OpenAPI 3.1. But for now it is still in 3.0

Hey,

would it be possible to release a v5.0.0-beta.1 that includes this fix?

**Comment by DenuxPlays** [comment]
I think this can be closed now.

Wasn't an issue with this crate.

**Comment by juhaku** [comment]
> Hey,
>
> would it be possible to release a v5.0.0-beta.1 that includes this fix?

I'll see if I could release a patch release for the 4.x.x serie. Though I could release the `5.0.0.alpha.1` as soon as I get my current work ready for PR and possibly even to master.

**Comment by juhaku** [comment]
@DenuxPlays Published another pre-release with the fix: https://github.com/juhaku/utoipa/issues/976#issuecomment-2254124781 

https://github.com/juhaku/utoipa/releases/tag/utoipa-5.0.0-alpha.1
